import Link from 'next/link'
import { AdminShell } from '@/components/admin-shell'
import { Flash } from '@/components/flash'
import { SubmitButton } from '@/components/submit-button'
import { addPoolItem, setPoolStatus, finalizePoolItem } from '@/app/actions/admin'
import { createPoolV2, setPoolPickupOptions, updateDraftPool, resetPoolToDraft } from '@/app/actions/pools'
import { enterPlanningTier, enterFinalSupplierQuote, recordSupplierReceipt } from '@/app/actions/pilot'
import { requireAdmin } from '@/lib/auth'
import { StatusPill } from '@/components/status-pill'
import { taka, shortDate, dateTime } from '@/lib/format'

export const dynamic='force-dynamic'
const nextStatus:Record<string,string>={draft:'open',open:'pricing',pricing:'final_price',final_price:'confirmation',confirmation:'ordered',ordered:'ready_for_pickup',ready_for_pickup:'completed'}
const dt=(value:string|null)=>value?new Date(value).toISOString().slice(0,16):''

export default async function Page({searchParams}:{searchParams:Promise<{error?:string;notice?:string}>}){
  const {supabase:db}=await requireAdmin(); const sp=await searchParams
  const results=await Promise.all([
    db.from('communities').select('id,name').eq('active',true).order('sort_order'),
    db.from('products').select('id,name,package_size').eq('active',true).order('name'),
    db.from('suppliers').select('id,business_name').eq('active',true).order('business_name'),
    db.from('pickup_points').select('id,community_id,name,address').eq('active',true).order('name'),
    db.from('pools').select('id,community_id,title,status,cadence,opens_at,commitment_closes_at,confirmation_closes_at,supplier_delivery_at,pickup_at,receiving_pickup_point_id,created_at,notes').order('created_at',{ascending:false}).limit(30),
  ])
  const [communitiesR,productsR,suppliersR,pickupsR,poolsR]=results
  const [poolItemsR,quotesR,commitmentsR,poolPickupR,benchmarksR,ordersR,receiptsR]=await Promise.all([
    db.from('pool_items').select('id,pool_id,product_id,benchmark_price_snapshot,expected_pool_price,final_customer_price,min_quantity,max_quantity,active,selected_supplier_quote_id,frozen_committed_quantity,frozen_tier_threshold,frozen_customer_ceiling_price,pricing_locked_at'),
    db.from('supplier_quotes').select('id,pool_item_id,supplier_id,quote_phase,threshold_quantity,quantity,quoted_unit_price,delivery_cost,landed_unit_price,customer_ceiling_price,available_quantity,delivery_included,delivery_target_at,valid_until,selected,selection_reason'),
    db.from('commitments').select('id,pool_item_id,quantity,status'),
    db.from('pool_pickup_points').select('pool_id,pickup_point_id'),
    db.from('market_price_benchmarks').select('product_id,community_id,benchmark_price').eq('approved',true).is('superseded_at',null),
    db.from('orders').select('id,pool_id,status'),
    db.from('supplier_receipts').select('id,pool_item_id,supplier_quote_id,expected_quantity,received_quantity,status,received_at,received_by,notes'),
  ])
  const communities=communitiesR.data??[],products=productsR.data??[],suppliers=suppliersR.data??[],pickups=pickupsR.data??[],pools=poolsR.data??[]
  const poolItems=poolItemsR.data??[],quotes=quotesR.data??[],commitments=commitmentsR.data??[],poolPickupRows=poolPickupR.data??[],benchmarks=benchmarksR.data??[],orders=ordersR.data??[],receipts=receiptsR.data??[]
  const communityById=new Map(communities.map((x:any)=>[x.id,x])),productById=new Map(products.map((x:any)=>[x.id,x])),supplierById=new Map(suppliers.map((x:any)=>[x.id,x]))
  const selectedPickups=new Map<string,Set<string>>(); poolPickupRows.forEach((r:any)=>{if(!selectedPickups.has(r.pool_id))selectedPickups.set(r.pool_id,new Set());selectedPickups.get(r.pool_id)!.add(r.pickup_point_id)})
  const itemsByPool=new Map<string,any[]>(); poolItems.forEach((i:any)=>{if(!itemsByPool.has(i.pool_id))itemsByPool.set(i.pool_id,[]);itemsByPool.get(i.pool_id)!.push(i)})
  const quotesByItem=new Map<string,any[]>(); quotes.forEach((q:any)=>{if(!quotesByItem.has(q.pool_item_id))quotesByItem.set(q.pool_item_id,[]);quotesByItem.get(q.pool_item_id)!.push(q)})
  const commitmentsByItem=new Map<string,any[]>(); commitments.forEach((c:any)=>{if(!commitmentsByItem.has(c.pool_item_id))commitmentsByItem.set(c.pool_item_id,[]);commitmentsByItem.get(c.pool_item_id)!.push(c)})
  const receiptByItem=new Map((receipts??[]).map((r:any)=>[r.pool_item_id,r]));const benchmarkByKey=new Map(benchmarks.map((b:any)=>[`${b.community_id}:${b.product_id}`,Number(b.benchmark_price)]))
  return <AdminShell><div className="grid min-w-0 gap-5">
    <section><h1 className="text-2xl font-black sm:text-3xl">Pools</h1><p className="muted mt-1">Pilot flow: Draft → planning tiers → Open demand → frozen Pricing → final negotiation → Confirmation → Ordered → supplier receipt → pickup.</p></section>
    <Flash {...sp}/>
    <form action={createPoolV2} className="card form-grid">
      <h2 className="section-title md:col-span-2">Create a new draft pool</h2>
      <label><span className="label">Pool cycle</span><select className="input" name="cadence" defaultValue="weekly"><option value="weekly">Weekly</option><option value="monthly">Monthly</option></select></label>
      <label><span className="label">Visible to community</span><select className="input" name="community_id" required><option value="">Choose community</option>{communities.map((c:any)=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label>
      <label className="md:col-span-2"><span className="label">Pool title</span><input className="input" name="title" placeholder="Amin Model Town Weekly Grocery Pool" required/></label>
      <label><span className="label">Opens at</span><input className="input" type="datetime-local" name="opens_at"/></label>
      <label><span className="label">Commitment closes</span><input className="input" type="datetime-local" name="commitment_closes_at"/></label>
      <label><span className="label">Confirmation closes</span><input className="input" type="datetime-local" name="confirmation_closes_at"/></label>
      <label><span className="label">Supplier delivery target</span><input className="input" type="datetime-local" name="supplier_delivery_at"/></label>
      <label><span className="label">Customer pickup starts</span><input className="input" type="datetime-local" name="pickup_at"/></label>
      <label><span className="label">Designated receiving point</span><select className="input" name="receiving_pickup_point_id"><option value="">Choose after community</option>{pickups.map((p:any)=><option key={p.id} value={p.id}>{(communityById.get(p.community_id) as any)?.name} · {p.name}</option>)}</select></label>
      <textarea className="input min-h-20 md:col-span-2" name="notes" placeholder="Operational notes"/>
      <SubmitButton>Create draft</SubmitButton>
    </form>
    <section className="flex flex-col gap-1 sm:flex-row sm:items-end sm:justify-between"><div><div className="card-title">Existing pools</div><h2 className="text-2xl font-black">Manage your created pools</h2><p className="muted mt-1">Supplier prices stay private. Customers see only benchmarks, demand, unlocked ceilings and final customer price.</p></div><span className="chip">{pools.length} pool{pools.length===1?'':'s'}</span></section>
    {pools.length===0?<div className="card"><b>No pools found.</b></div>:<div className="grid gap-5">{pools.map((p:any)=>{
      const chosen=selectedPickups.get(p.id)??new Set<string>(),communityPickups=pickups.filter((x:any)=>x.community_id===p.community_id),items=itemsByPool.get(p.id)??[]
      const eligibleProducts=products.filter((x:any)=>benchmarkByKey.has(`${p.community_id}:${x.id}`)),community=communityById.get(p.community_id) as any
      const poolCommitments=items.flatMap((i:any)=>commitmentsByItem.get(i.id)??[]),poolQuotes=items.flatMap((i:any)=>quotesByItem.get(i.id)??[]),poolOrders=orders.filter((o:any)=>o.pool_id===p.id)
      const hasFinalQuotes=poolQuotes.some((q:any)=>q.quote_phase==='final')
      const canReturnToDraft=['open','pricing'].includes(p.status)&&poolCommitments.length===0&&!hasFinalQuotes&&poolOrders.length===0
      return <section className="card border-slate-300" key={p.id}>
        <div className="flex flex-col gap-3 sm:flex-row sm:items-start sm:justify-between"><div><div className="flex flex-wrap items-center gap-2"><span className="chip capitalize">{p.cadence??'weekly'}</span><span className="text-xs font-bold uppercase text-slate-500">{community?.name}</span></div><h2 className="mt-2 text-xl font-black sm:text-2xl">{p.title}</h2><p className="muted mt-1">Created {shortDate(p.created_at)} · {items.length} item{items.length===1?'':'s'} · supplier handover {p.supplier_delivery_at?dateTime(p.supplier_delivery_at):'not set'} · pickup {p.pickup_at?dateTime(p.pickup_at):'not set'}</p></div><StatusPill status={p.status}/></div>
        {canReturnToDraft&&<div className="notice mt-4 flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"><div><b>No customer/commercial activity yet.</b><p className="mt-1">Return to Draft if this pool was advanced by mistake.</p></div><form action={resetPoolToDraft}><input type="hidden" name="pool_id" value={p.id}/><SubmitButton className="btn-secondary">Return to Draft</SubmitButton></form></div>}
        {p.status==='draft'&&<form action={updateDraftPool} className="mt-4 grid gap-3 rounded-xl border border-slate-200 bg-white p-3 md:grid-cols-2">
          <input type="hidden" name="pool_id" value={p.id}/><div className="md:col-span-2"><b>1. Pool setup & handover timing</b><p className="muted">Supplier handover must happen after confirmation closes and before customer pickup starts.</p></div>
          <label><span className="label">Pool title</span><input className="input" name="title" defaultValue={p.title} required/></label>
          <label><span className="label">Cycle</span><select className="input" name="cadence" defaultValue={p.cadence??'weekly'}><option value="weekly">Weekly</option><option value="monthly">Monthly</option></select></label>
          <label><span className="label">Opens at</span><input className="input" type="datetime-local" name="opens_at" defaultValue={dt(p.opens_at)}/></label>
          <label><span className="label">Commitment closes</span><input className="input" type="datetime-local" name="commitment_closes_at" defaultValue={dt(p.commitment_closes_at)}/></label>
          <label><span className="label">Confirmation closes</span><input className="input" type="datetime-local" name="confirmation_closes_at" defaultValue={dt(p.confirmation_closes_at)}/></label>
          <label><span className="label">Supplier delivery target</span><input className="input" type="datetime-local" name="supplier_delivery_at" defaultValue={dt(p.supplier_delivery_at)}/></label>
          <label><span className="label">Customer pickup starts</span><input className="input" type="datetime-local" name="pickup_at" defaultValue={dt(p.pickup_at)}/></label>
          <label><span className="label">Designated receiving point</span><select className="input" name="receiving_pickup_point_id" defaultValue={p.receiving_pickup_point_id??''}><option value="">Choose point</option>{communityPickups.map((point:any)=><option key={point.id} value={point.id}>{point.name} · {point.address}</option>)}</select></label>
          <label className="md:col-span-2"><span className="label">Notes</span><textarea className="input min-h-20" name="notes" defaultValue={p.notes??''}/></label>
          <SubmitButton className="md:w-fit">Save draft setup</SubmitButton>
        </form>}
        {p.status==='draft'&&<div className="mt-4 rounded-xl border border-slate-200 bg-slate-50 p-3"><div className="mb-3"><b>2. Add products</b><p className="muted">Only products with an approved community benchmark can enter the pool. The old expected-price field is internal only; customer pricing comes from planning tiers below.</p></div>{eligibleProducts.length?<form action={addPoolItem} className="grid gap-2 md:grid-cols-4"><input type="hidden" name="pool_id" value={p.id}/><label className="md:col-span-2"><span className="label">Product</span><select className="input" name="product_id" required><option value="">Choose product</option>{eligibleProducts.map((x:any)=><option key={x.id} value={x.id}>{x.name} · {x.package_size} · benchmark {taka(benchmarkByKey.get(`${p.community_id}:${x.id}`)??0)}</option>)}</select></label><label><span className="label">Max / household</span><input className="input" type="number" min="1" name="max_quantity" defaultValue="20"/></label><div className="self-end"><SubmitButton className="w-full">Add product</SubmitButton></div></form>:<div className="notice">Approve a current benchmark in <Link href="/admin/market-prices" className="font-black underline">Market prices</Link> first.</div>}</div>}
        {!['completed','cancelled'].includes(p.status)&&<form action={setPoolPickupOptions} className="mt-4 rounded-xl border border-slate-200 bg-slate-50 p-3"><input type="hidden" name="pool_id" value={p.id}/><div className="flex flex-col gap-2 sm:flex-row sm:items-center sm:justify-between"><div><b>{p.status==='draft'?'3':'Pickup'}. Available customer pickup choices</b><p className="muted">The designated supplier receiving point must be included here too.</p></div><SubmitButton className="btn-secondary">Save pickup options</SubmitButton></div><div className="mt-3 grid gap-2 sm:grid-cols-2 lg:grid-cols-3">{communityPickups.map((point:any)=><label key={point.id} className="flex gap-2 rounded-xl border border-slate-200 bg-white p-3 text-sm"><input type="checkbox" name="pickup_point_ids" value={point.id} defaultChecked={chosen.has(point.id)}/><span><b>{point.name}</b><br/><span className="text-slate-500">{point.address}</span>{p.receiving_pickup_point_id===point.id&&<><br/><span className="font-bold text-emerald-700">Supplier receiving point</span></>}</span></label>)}</div></form>}
        <div className="mt-4 grid gap-3"><h3 className="font-black">{p.status==='draft'?'4':'Items'}. Items in this pool ({items.length})</h3>{items.length===0?<div className="rounded-xl border border-dashed border-slate-300 p-4 text-sm text-slate-500">No product has been added yet.</div>:items.map((i:any)=>{
          const product=productById.get(i.product_id) as any,itemQuotes=quotesByItem.get(i.id)??[],planningQuotes=itemQuotes.filter((q:any)=>q.quote_phase==='planning_tier').sort((a:any,b:any)=>Number(a.threshold_quantity)-Number(b.threshold_quantity)),finalQuotes=itemQuotes.filter((q:any)=>q.quote_phase==='final')
          const itemCommitments=commitmentsByItem.get(i.id)??[],demand=itemCommitments.filter((c:any)=>['active','confirmed'].includes(c.status)).reduce((s:number,c:any)=>s+Number(c.quantity),0),receipt=receiptByItem.get(i.id) as any
          const selectedQuote=finalQuotes.find((q:any)=>q.id===i.selected_supplier_quote_id),margin=i.final_customer_price&&selectedQuote?Number(i.final_customer_price)-Number(selectedQuote.landed_unit_price):null
          return <article className="min-w-0 rounded-xl border border-slate-200 bg-white/70 p-3" key={i.id}>
            <div className="flex flex-col gap-2 sm:flex-row sm:items-start sm:justify-between"><div><b>{product?.name} · {product?.package_size}</b><p className="muted">Benchmark {taka(i.benchmark_price_snapshot)} · live demand {demand} · final {i.final_customer_price?taka(i.final_customer_price):'pending'}</p></div>{i.pricing_locked_at&&<span className="chip">Demand frozen</span>}</div>
            {i.pricing_locked_at&&<div className="mt-3 grid gap-2 sm:grid-cols-3"><div className="rounded-xl bg-slate-50 p-3"><div className="card-title">Frozen quantity</div><b className="text-xl">{i.frozen_committed_quantity??0}</b></div><div className="rounded-xl bg-slate-50 p-3"><div className="card-title">Unlocked ceiling</div><b className="text-xl">{i.frozen_customer_ceiling_price?taka(i.frozen_customer_ceiling_price):'No tier reached'}</b></div><div className="rounded-xl bg-slate-50 p-3"><div className="card-title">Frozen tier</div><b className="text-xl">{i.frozen_tier_threshold?`${i.frozen_tier_threshold}+ units`:'—'}</b></div></div>}
            {p.status==='draft'&&<form action={enterPlanningTier} className="mt-3 grid gap-2 rounded-xl border border-blue-200 bg-blue-50/60 p-3 md:grid-cols-4"><input type="hidden" name="pool_item_id" value={i.id}/><div className="md:col-span-4"><b>Planning price tier</b><p className="muted">Private supplier delivered cost + public maximum customer price if this threshold is reached.</p></div><label><span className="label">Supplier</span><select className="input" name="supplier_id" required><option value="">Choose supplier</option>{suppliers.map((s:any)=><option key={s.id} value={s.id}>{s.business_name}</option>)}</select></label><label><span className="label">Threshold qty</span><input className="input" type="number" min="1" name="threshold_quantity" required/></label><label><span className="label">Supplier quoted / unit</span><input className="input" type="number" min="0.01" step="0.01" name="quoted_unit_price" required/></label><label><span className="label">Delivery cost</span><input className="input" type="number" min="0" step="0.01" name="delivery_cost" defaultValue="0"/></label><label><span className="label">Delivered landed / unit</span><input className="input" type="number" min="0.01" step="0.01" name="landed_unit_price" required/></label><label><span className="label">Customer ceiling / unlock</span><input className="input" type="number" min="0.01" step="0.01" name="customer_ceiling_price" required/></label><label><span className="label">Valid until</span><input className="input" type="date" name="valid_until"/></label><label><span className="label">Private note</span><input className="input" name="notes" placeholder="Delivery included to receiving point"/></label><SubmitButton className="md:w-fit">Save planning tier</SubmitButton></form>}
            {planningQuotes.length>0&&<div className="table-wrap mt-3"><table><thead><tr><th>Threshold</th><th>Supplier</th><th>Private landed</th><th>Customer unlock ceiling</th><th>Delivery</th></tr></thead><tbody>{planningQuotes.map((q:any)=><tr key={q.id}><td>{q.threshold_quantity}+ units</td><td>{(supplierById.get(q.supplier_id) as any)?.business_name}</td><td>{taka(q.landed_unit_price)}</td><td className="font-black">{taka(q.customer_ceiling_price)}</td><td>{q.delivery_included?'Included':'No'}</td></tr>)}</tbody></table></div>}
            {['pricing','final_price'].includes(p.status)&&<form action={enterFinalSupplierQuote} className="mt-3 grid gap-2 rounded-xl border border-emerald-200 bg-emerald-50/60 p-3 md:grid-cols-4"><input type="hidden" name="pool_item_id" value={i.id}/><div className="md:col-span-4"><b>Second / final supplier negotiation</b><p className="muted">Quote must cover the exact frozen quantity: {i.frozen_committed_quantity??0}. Supplier cost stays private.</p></div><label><span className="label">Supplier</span><select className="input" name="supplier_id" required><option value="">Choose supplier</option>{suppliers.map((s:any)=><option key={s.id} value={s.id}>{s.business_name}</option>)}</select></label><label><span className="label">Supplier quoted / unit</span><input className="input" type="number" min="0.01" step="0.01" name="quoted_unit_price" required/></label><label><span className="label">Delivery cost</span><input className="input" type="number" min="0" step="0.01" name="delivery_cost" defaultValue="0"/></label><label><span className="label">Final delivered landed / unit</span><input className="input" type="number" min="0.01" step="0.01" name="landed_unit_price" required/></label><label><span className="label">Payment terms</span><input className="input" name="payment_terms"/></label><label><span className="label">Valid until</span><input className="input" type="date" name="valid_until"/></label><label className="md:col-span-2"><span className="label">Private notes</span><input className="input" name="notes"/></label><SubmitButton className="md:w-fit">Save final supplier quote</SubmitButton></form>}
            {finalQuotes.length>0&&<div className="table-wrap mt-3"><table><thead><tr><th>Supplier</th><th>Qty</th><th>Private landed</th><th>Selected</th></tr></thead><tbody>{finalQuotes.map((q:any)=><tr key={q.id}><td>{(supplierById.get(q.supplier_id) as any)?.business_name}</td><td>{q.quantity}</td><td>{taka(q.landed_unit_price)}</td><td>{q.selected?'Yes':'No'}</td></tr>)}</tbody></table></div>}
            {['pricing','final_price'].includes(p.status)&&finalQuotes.length>0&&<form action={finalizePoolItem} className="mt-3 grid gap-2 rounded-xl border border-slate-200 bg-slate-50 p-3 md:grid-cols-4"><input type="hidden" name="pool_item_id" value={i.id}/><label><span className="label">Winning final quote</span><select className="input" name="quote_id" required><option value="">Choose final quote</option>{finalQuotes.map((q:any)=><option key={q.id} value={q.id}>{(supplierById.get(q.supplier_id) as any)?.business_name} · landed {taka(q.landed_unit_price)}</option>)}</select></label><label><span className="label">Final customer price</span><input className="input" type="number" min="0.01" step="0.01" name="final_customer_price" defaultValue={i.final_customer_price??''} placeholder={i.frozen_customer_ceiling_price?`≤ ${i.frozen_customer_ceiling_price}`:'Positive price'} required/></label><label><span className="label">Selection reason</span><input className="input" name="reason" required/></label><div className="self-end"><SubmitButton className="w-full">Finalize item</SubmitButton></div></form>}
            {selectedQuote&&i.final_customer_price&&<div className="mt-3 grid gap-2 sm:grid-cols-4"><div className="rounded-xl bg-slate-50 p-3"><div className="card-title">Frozen qty</div><b>{i.frozen_committed_quantity??0}</b></div><div className="rounded-xl bg-slate-50 p-3"><div className="card-title">Supplier landed</div><b>{taka(selectedQuote.landed_unit_price)}</b></div><div className="rounded-xl bg-slate-50 p-3"><div className="card-title">Final customer</div><b>{taka(i.final_customer_price)}</b></div><div className="rounded-xl bg-slate-50 p-3"><div className="card-title">Projected platform margin</div><b>{taka((margin??0)*Number(i.frozen_committed_quantity??0))}</b><p className="muted">{taka(margin??0)} / unit</p></div></div>}
            {['ordered','ready_for_pickup'].includes(p.status)&&selectedQuote&&<div className="mt-3 rounded-xl border border-indigo-200 bg-indigo-50/60 p-3"><div className="flex flex-col gap-2 sm:flex-row sm:items-start sm:justify-between"><div><b>Supplier delivery</b><p className="muted">Expected {selectedQuote.quantity} units · target {p.supplier_delivery_at?dateTime(p.supplier_delivery_at):'not set'} · receiving point {(communityPickups.find((x:any)=>x.id===p.receiving_pickup_point_id) as any)?.name??'not set'}</p></div><span className="chip capitalize">{receipt?.status??'awaiting receipt'}</span></div>{receipt&&<p className="mt-2 text-sm">Received <b>{receipt.received_quantity}/{receipt.expected_quantity}</b> · {dateTime(receipt.received_at)}{receipt.notes?` · ${receipt.notes}`:''}</p>}{p.status==='ordered'&&<form action={recordSupplierReceipt} className="mt-3 grid gap-2 sm:grid-cols-[160px_1fr_auto] sm:items-end"><input type="hidden" name="pool_item_id" value={i.id}/><label><span className="label">Received quantity</span><input className="input" type="number" min="0" name="received_quantity" defaultValue={receipt?.received_quantity??selectedQuote.quantity} required/></label><label><span className="label">Receiving note / issue</span><input className="input" name="notes" defaultValue={receipt?.notes??''} placeholder="Packaging checked; note shortage/damage"/></label><SubmitButton>Record receipt</SubmitButton></form>}</div>}
          </article>})}</div>
        {nextStatus[p.status]&&<div className="mt-4 rounded-xl border border-slate-200 bg-white p-3"><b>Advance this pool</b><p className="muted mt-1">Backend guards freeze demand, enforce the price ceiling and block pickup before supplier receipt.</p><div className="mt-3 flex flex-col gap-2 sm:flex-row sm:flex-wrap"><form action={setPoolStatus}><input type="hidden" name="pool_id" value={p.id}/><input type="hidden" name="status" value={nextStatus[p.status]}/><SubmitButton className="w-full sm:w-auto">Move to {nextStatus[p.status].replaceAll('_',' ')}</SubmitButton></form>{p.status!=='ready_for_pickup'&&<form action={setPoolStatus}><input type="hidden" name="pool_id" value={p.id}/><input type="hidden" name="status" value="cancelled"/><SubmitButton className="btn-danger w-full sm:w-auto">Cancel pool</SubmitButton></form>}</div></div>}
      </section>})}</div>}
  </div></AdminShell>
}
