'use server'

import { revalidatePath } from 'next/cache'
import { redirect } from 'next/navigation'
import { requireAdmin } from '@/lib/auth'

const t=(fd:FormData,k:string)=>String(fd.get(k)??'').trim()
const n=(fd:FormData,k:string)=>Number(t(fd,k))
const isoOrNull=(v:string)=>v?new Date(v).toISOString():null

function done(path:string,message:string){revalidatePath('/admin','layout');redirect(`${path}?notice=${encodeURIComponent(message)}`)}
function fail(path:string,message:string):never{redirect(`${path}?error=${encodeURIComponent(message)}`)}

export async function createCommunity(fd:FormData){const {supabase}=await requireAdmin();const name=t(fd,'name'),slug=t(fd,'slug').toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'');if(!name||!slug)fail('/admin/communities','Name and slug required');const {error}=await supabase.from('communities').insert({name,slug,sort_order:n(fd,'sort_order')||100});if(error)fail('/admin/communities',error.message);done('/admin/communities','Community created')}

export async function createProduct(fd:FormData){const {supabase}=await requireAdmin();const payload={name:t(fd,'name'),brand:t(fd,'brand')||null,category:t(fd,'category'),package_size:t(fd,'package_size'),unit:t(fd,'unit'),sku:t(fd,'sku').toUpperCase(),image_url:t(fd,'image_url')||null,is_demo:fd.get('is_demo')==='on'};if(!payload.name||!payload.category||!payload.package_size||!payload.unit||!payload.sku)fail('/admin/products','Complete required product fields');const {error}=await supabase.from('products').insert(payload);if(error)fail('/admin/products',error.message);done('/admin/products','Product created')}

export async function createPickupPoint(fd:FormData){const {supabase}=await requireAdmin();const payload={community_id:t(fd,'community_id'),name:t(fd,'name'),contact_name:t(fd,'contact_name')||null,contact_phone:t(fd,'contact_phone')||null,address:t(fd,'address'),google_maps_url:t(fd,'google_maps_url')||null,opening_hours:t(fd,'opening_hours')||null};if(!payload.community_id||!payload.name||!payload.address)fail('/admin/pickup-points','Community, name and address are required');const {error}=await supabase.from('pickup_points').insert(payload);if(error)fail('/admin/pickup-points',error.message);done('/admin/pickup-points','Pickup point created')}

export async function assignPickupOperator(fd:FormData){const {supabase}=await requireAdmin();const userId=t(fd,'user_id'),pointId=t(fd,'pickup_point_id');if(!userId||!pointId)fail('/admin/pickup-points','Choose operator and pickup point');const {error}=await supabase.from('pickup_operator_assignments').upsert({user_id:userId,pickup_point_id:pointId});if(error)fail('/admin/pickup-points',error.message);done('/admin/pickup-points','Pickup operator assigned')}

export async function createSupplier(fd:FormData){const {supabase}=await requireAdmin();const payload={business_name:t(fd,'business_name'),contact_person:t(fd,'contact_person')||null,mobile:t(fd,'mobile')||null,location:t(fd,'location')||null,product_categories:t(fd,'product_categories')||null,notes:t(fd,'notes')||null,reliability_status:t(fd,'reliability_status')||'unrated'};if(!payload.business_name)fail('/admin/suppliers','Business name required');const {error}=await supabase.from('suppliers').insert(payload);if(error)fail('/admin/suppliers',error.message);done('/admin/suppliers','Supplier created')}

export async function recordMarketObservation(fd:FormData){const {supabase,user}=await requireAdmin();const price=n(fd,'observed_price');const payload={product_id:t(fd,'product_id'),community_id:t(fd,'community_id'),observed_price:price,source_store:t(fd,'source_store'),observed_on:t(fd,'observed_on')||new Date().toISOString().slice(0,10),notes:t(fd,'notes')||null,created_by:user.id};if(!payload.product_id||!payload.community_id||!payload.source_store||!(price>0))fail('/admin/market-prices','Complete product, community, store and positive price');const {error}=await supabase.from('market_price_observations').insert(payload);if(error)fail('/admin/market-prices',error.message);done('/admin/market-prices','Market observation recorded')}

export async function approveBenchmark(fd:FormData){const {supabase}=await requireAdmin();const price=n(fd,'benchmark_price');const {error}=await supabase.rpc('admin_approve_benchmark',{p_product_id:t(fd,'product_id'),p_community_id:t(fd,'community_id'),p_price:price,p_method:t(fd,'method')||'median/reasonable verified local-market price'});if(error)fail('/admin/market-prices',error.message);done('/admin/market-prices','Benchmark approved')}

export async function createPool(fd:FormData){const {supabase,user}=await requireAdmin();const payload={community_id:t(fd,'community_id'),title:t(fd,'title'),status:'draft',opens_at:isoOrNull(t(fd,'opens_at')),commitment_closes_at:isoOrNull(t(fd,'commitment_closes_at')),confirmation_closes_at:isoOrNull(t(fd,'confirmation_closes_at')),pickup_at:isoOrNull(t(fd,'pickup_at')),notes:t(fd,'notes')||null,created_by:user.id};if(!payload.community_id||!payload.title)fail('/admin/pools','Community and title required');const {error}=await supabase.from('pools').insert(payload);if(error)fail('/admin/pools',error.message);done('/admin/pools','Draft pool created')}

export async function addPoolItem(fd:FormData){const {supabase}=await requireAdmin();const poolId=t(fd,'pool_id'),productId=t(fd,'product_id');const {data:pool,error:poolError}=await supabase.from('pools').select('community_id,status').eq('id',poolId).single();if(poolError||!pool)fail('/admin/pools','Pool not found');if(pool.status!=='draft')fail('/admin/pools','Items can only be added while pool is draft');const {data:benchmark,error:bError}=await supabase.from('market_price_benchmarks').select('id,benchmark_price').eq('product_id',productId).eq('community_id',pool.community_id).eq('approved',true).is('superseded_at',null).maybeSingle();if(bError||!benchmark)fail('/admin/pools','Approve a current market benchmark for this product/community first');const expected=n(fd,'expected_pool_price');const {error}=await supabase.from('pool_items').insert({pool_id:poolId,product_id:productId,benchmark_id:benchmark.id,benchmark_price_snapshot:benchmark.benchmark_price,expected_pool_price:expected>0?expected:null,min_quantity:n(fd,'min_quantity')||1,max_quantity:n(fd,'max_quantity')||20});if(error)fail('/admin/pools',error.message);done('/admin/pools','Product added with benchmark snapshot')}

export async function setPoolStatus(fd:FormData){const {supabase}=await requireAdmin();const {error}=await supabase.rpc('admin_set_pool_status',{p_pool_id:t(fd,'pool_id'),p_status:t(fd,'status')});if(error)fail('/admin/pools',error.message);done('/admin/pools',`Pool moved to ${t(fd,'status').replaceAll('_',' ')}`)}

export async function enterSupplierQuote(fd:FormData){const {supabase,user}=await requireAdmin();const payload={pool_item_id:t(fd,'pool_item_id'),supplier_id:t(fd,'supplier_id'),quantity:n(fd,'quantity'),quoted_unit_price:n(fd,'quoted_unit_price'),delivery_cost:n(fd,'delivery_cost')||0,landed_unit_price:n(fd,'landed_unit_price'),available_quantity:n(fd,'available_quantity')||null,delivery_date:t(fd,'delivery_date')||null,payment_terms:t(fd,'payment_terms')||null,valid_until:t(fd,'valid_until')||null,notes:t(fd,'notes')||null,created_by:user.id};if(!payload.pool_item_id||!payload.supplier_id||!(payload.quantity>0)||!(payload.quoted_unit_price>0)||!(payload.landed_unit_price>0))fail('/admin/pools','Complete required quote fields');const {error}=await supabase.from('supplier_quotes').insert(payload);if(error)fail('/admin/pools',error.message);done('/admin/pools','Supplier quotation recorded')}

export async function finalizePoolItem(fd:FormData){const {supabase}=await requireAdmin();const {error}=await supabase.rpc('admin_finalize_pool_item',{p_pool_item_id:t(fd,'pool_item_id'),p_quote_id:t(fd,'quote_id'),p_final_customer_price:n(fd,'final_customer_price'),p_reason:t(fd,'reason')});if(error)fail('/admin/pools',error.message);done('/admin/pools','Winning quote and customer price saved')}

export async function updateOrderPayment(fd:FormData){const {supabase}=await requireAdmin();const rawAmount=t(fd,'amount'),amount=rawAmount===''?null:Number(rawAmount);if(amount!==null&&(!Number.isFinite(amount)||amount<0))fail('/admin/orders','Payment amount must be zero or positive');const {error}=await supabase.rpc('admin_update_payment',{p_order_id:t(fd,'order_id'),p_status:t(fd,'payment_status'),p_method:t(fd,'payment_method')||null,p_reference:t(fd,'payment_reference')||null,p_amount:amount,p_notes:t(fd,'notes')||null});if(error)fail('/admin/orders',error.message);done('/admin/orders','Payment status updated')}

export async function cancelOrder(fd:FormData){const {supabase}=await requireAdmin();const reason=t(fd,'reason');if(!reason)fail('/admin/orders','Cancellation reason required');const {error}=await supabase.rpc('admin_cancel_order',{p_order_id:t(fd,'order_id'),p_reason:reason});if(error)fail('/admin/orders',error.message);done('/admin/orders','Order cancelled; no savings will be generated')}

export async function resolveIssue(fd:FormData){const {supabase}=await requireAdmin();const id=t(fd,'issue_id');const {error}=await supabase.from('operational_issues').update({status:'resolved',resolution_notes:t(fd,'resolution_notes')||null,resolved_at:new Date().toISOString()}).eq('id',id);if(error)fail('/admin/issues',error.message);done('/admin/issues','Issue resolved')}
