'use server'
import { revalidatePath } from 'next/cache'
import { redirect } from 'next/navigation'
import { requirePickupOperator } from '@/lib/auth'

export async function recordInboundReceipt(fd:FormData){const {supabase}=await requirePickupOperator();const poolItemId=String(fd.get('pool_item_id')??'');const qty=Number(String(fd.get('received_quantity')??''));const notes=String(fd.get('notes')??'').trim()||null;if(!poolItemId||!Number.isInteger(qty)||qty<0)redirect('/pickup-ops?error=Enter+a+valid+received+quantity');const {error}=await supabase.rpc('record_supplier_receipt',{p_pool_item_id:poolItemId,p_received_quantity:qty,p_notes:notes});if(error)redirect(`/pickup-ops?error=${encodeURIComponent(error.message)}`);revalidatePath('/pickup-ops');redirect('/pickup-ops?notice=Supplier+delivery+receipt+recorded')}

export async function markCollected(fd:FormData){const {supabase}=await requirePickupOperator();const orderId=String(fd.get('order_id')??'');const notes=String(fd.get('notes')??'').trim()||null;const {data,error}=await supabase.rpc('mark_order_collected',{p_order_id:orderId,p_notes:notes});if(error)redirect(`/pickup-ops?error=${encodeURIComponent(error.message)}`);revalidatePath('/pickup-ops');revalidatePath('/savings');redirect(`/pickup-ops?notice=${encodeURIComponent(`Collected. Verified savings credited: ৳${Number(data??0).toLocaleString('en-BD')}`)}`)}

export async function reportPickupIssue(fd:FormData){const {supabase,user}=await requirePickupOperator();const orderId=String(fd.get('order_id')??'');const description=String(fd.get('description')??'').trim();if(description.length<5)redirect('/pickup-ops?error=Describe+the+issue');if(description.length>2000)redirect('/pickup-ops?error=Keep+the+issue+within+2000+characters');const {error}=await supabase.from('operational_issues').insert({order_id:orderId,reported_by:user.id,issue_type:'pickup_issue',description});if(error)redirect(`/pickup-ops?error=${encodeURIComponent(error.message)}`);redirect('/pickup-ops?notice=Issue+reported')}
