import test from 'node:test'
import assert from 'node:assert/strict'
import { readFileSync } from 'node:fs'

const read=(rel)=>readFileSync(new URL(`../${rel}`,import.meta.url),'utf8')

test('customer confirmation requires current policy acceptance',()=>{
  const page=read('app/orders/page.tsx')
  const action=read('app/actions/customer.ts')
  assert.match(page,/policy_accepted/)
  assert.match(page,/CURRENT_POLICY_VERSION/)
  assert.match(page,/Terms & Conditions \/ ব্যবহারের শর্তাবলি/)
  assert.match(page,/Return Policy \/ রিটার্ন নীতি/)
  assert.match(page,/Refund Policy \/ রিফান্ড নীতি/)
  assert.match(action,/policyAccepted/)
  assert.match(action,/policyVersion !== CURRENT_POLICY_VERSION/)
})

test('bilingual legal pages and footer links exist',()=>{
  for(const file of ['app/privacy/page.tsx','app/terms/page.tsx','app/return-policy/page.tsx','app/refund-policy/page.tsx']){
    const content=read(file)
    assert.match(content,/titleBn/)
    assert.match(content,/summaryBn/)
  }
  const links=read('lib/legal.ts')
  assert.match(links,/\/about/);assert.match(links,/\/privacy/);assert.match(links,/\/terms/);assert.match(links,/\/return-policy/);assert.match(links,/\/refund-policy/)
})

test('public SEO AEO GEO discovery assets are present',()=>{
  const layout=read('app/layout.tsx')
  const home=read('app/page.tsx')
  const site=read('lib/site.ts')
  const robots=read('app/robots.ts')
  const sitemap=read('app/sitemap.ts')
  const llms=read('app/llms.txt/route.ts')
  const proxy=read('proxy.ts')

  assert.match(layout,/metadataBase/)
  assert.match(site,/SITE_TAGLINE_EN = 'Smart shopping\. Real savings!'/)
  assert.match(site,/SITE_TAGLINE_BN = 'একসাথে কিনি, কম দামে পাই!'/)
  assert.match(site,/Community Pools and nearby Group Deals/)
  assert.match(site,/SEO_UPDATED_AT = '2026-10-09T00:00:00\+06:00'/)
  assert.match(layout,/title: \{ default: \`\$\{SITE_NAME\} \| \$\{SITE_TAGLINE_EN\}\`/)
  assert.doesNotMatch(layout,/Community Grocery Pooling in Savar/)
  assert.doesNotMatch(layout,/alternates:\s*\{\s*canonical:/)
  assert.match(home,/alternates:\s*\{\s*canonical:\s*SITE_URL/)
  assert.match(home,/title:\s*\{\s*absolute:\s*\`\$\{SITE_NAME\} \| \$\{SITE_TAGLINE_EN\}\`\s*\}/)
  assert.match(home,/slogan:\s*SITE_TAGLINE_EN/)
  assert.doesNotMatch(home,/Community Grocery Pooling in Savar/)
  assert.match(home,/application\/ld\+json/)
  assert.match(home,/WebPage/)
  assert.match(home,/ImageObject/)
  assert.match(home,/ContactPoint/)
  assert.match(site,/https:\/\/2takarbazar\.com/)
  assert.match(read('app/about/page.tsx'),/AboutPage/)
  assert.match(read('app/about/page.tsx'),/BreadcrumbList/)
  assert.match(read('app/faq/page.tsx'),/FAQPage/)
  assert.match(read('app/faq/page.tsx'),/BreadcrumbList/)
  assert.match(robots,/OAI-SearchBot/)
  assert.match(robots,/OAI-AdsBot/)
  assert.match(robots,/sitemap\.xml/)
  assert.match(robots,/\/money/)
  assert.match(robots,/\/group-deals/)
  assert.match(robots,/\/supplier/)
  assert.match(robots,/\/preview-demo/)
  assert.match(robots,/\/community-invite/)
  assert.match(robots,/\/qr\//)
  assert.match(sitemap,/SEO_UPDATED_AT/)
  assert.match(sitemap,/\/about/)
  assert.match(sitemap,/\/privacy/)
  assert.match(sitemap,/refund-policy/)
  assert.match(llms,/two customer buying modes/i)
  assert.match(llms,/Group Deals/)
  assert.match(llms,/Community QR links/)
  assert.match(llms,/Privacy Policy/)
  assert.match(llms,/SITE_URL/)
  assert.match(proxy,/X-Robots-Tag/)
  assert.match(proxy,/noindex, nofollow, noarchive/)
  assert.match(proxy,/\/money/)
  assert.match(proxy,/\/group-deals/)
  assert.match(proxy,/\/supplier/)
  assert.match(proxy,/\/preview-demo/)
  assert.match(proxy,/\/qr/)
  assert.match(read('app/group-deals/page.tsx'),/robots:\s*\{\s*index:\s*false/)
  assert.match(read('app/supplier/page.tsx'),/robots:\s*\{\s*index:\s*false/)
  assert.match(read('app/preview-demo/page.tsx'),/robots:\s*\{\s*index:\s*false/)
  assert.match(read('app/qr/[code]/route.ts'),/X-Robots-Tag.*noindex, noimageindex, noarchive/)
  assert.match(read('app/about/page.tsx'),/Community Pools and Group Deals/)
  assert.match(read('app/faq/page.tsx'),/difference between a Community Pool and a Group Deal/)
  assert.match(read('app/faq/page.tsx'),/community QR code/)
})


test('first-touch bilingual UX keeps English primary and Bangla compact',()=>{
  const login=read('app/login/page.tsx')
  const publicHome=read('app/page.tsx')
  const memberHome=read('app/home/page.tsx')
  const about=read('app/about/page.tsx')
  const policy=read('components/policy-page.tsx')
  assert.match(login,/সাইন ইন করুন/)
  assert.match(publicHome,/কীভাবে কাজ করে/)
  assert.doesNotMatch(login,/actionLabelBn/)
  assert.doesNotMatch(publicHome,/actionLabelBn/)
  assert.match(memberHome,/আপনার কমিউনিটি আরও স্মার্টভাবে বাজার করছে/)
  assert.match(about,/কার জন্য তৈরি\?/)
  assert.match(policy,/text-\[13px\]/)
  assert.match(read('app/privacy/page.tsx'),/গোপনীয়তা নীতি/)
})


test('action buttons stay English-only and footer stacks Bangla under English',()=>{
  const publicHeader=read('components/public-header.tsx')
  const publicHome=read('app/page.tsx')
  const login=read('app/login/page.tsx')
  const memberHome=read('app/home/page.tsx')
  const siteFooter=read('components/site-footer.tsx')
  const appShell=read('components/app-shell.tsx')
  assert.doesNotMatch(publicHeader,/actionLabelBn/)
  assert.doesNotMatch(publicHome,/btn-primary[^>]*>[\s\S]{0,200}lang="bn"/)
  assert.doesNotMatch(login,/SubmitButton>[\s\S]{0,120}lang="bn"/)
  assert.doesNotMatch(memberHome,/btn-primary[^>]*>[\s\S]{0,160}lang="bn"/)
  assert.match(siteFooter,/grid-cols-2/)
  assert.match(siteFooter,/sm:grid-cols-3/)
  assert.match(siteFooter,/labelBn/)
  assert.match(appShell,/SiteFooter withMobileNavOffset/)
})


test('footer legal labels use hard stacked containers and action links stay English-only',()=>{
  const siteFooter=read('components/site-footer.tsx')
  const appShell=read('components/app-shell.tsx')
  const publicHome=read('app/page.tsx')
  const memberHome=read('app/home/page.tsx')
  assert.match(siteFooter,/site-footer-link-en/)
  assert.match(siteFooter,/site-footer-link-bn/)
  assert.match(appShell,/SiteFooter withMobileNavOffset/)
  assert.doesNotMatch(publicHome,/About the model →<\/span>/)
  assert.doesNotMatch(publicHome,/Read FAQ →<\/span>/)
  assert.doesNotMatch(memberHome,/View all → <span/)
})


test('all public and signed-in pages share one footer implementation with forced EN-BN stacking',()=>{
  const publicFooter=read('components/public-footer.tsx')
  const siteFooter=read('components/site-footer.tsx')
  const appShell=read('components/app-shell.tsx')
  const css=read('app/globals.css')
  assert.match(publicFooter,/SiteFooter/)
  assert.match(appShell,/SiteFooter withMobileNavOffset/)
  assert.match(siteFooter,/site-footer-link-en/)
  assert.match(siteFooter,/site-footer-link-bn/)
  assert.match(css,/\.site-footer-link\s*\{[\s\S]*display:\s*flex\s*!important/)
  assert.match(css,/flex-direction:\s*column\s*!important/)
  assert.match(css,/\.site-footer-link-en,[\s\S]*\.site-footer-link-bn[\s\S]*display:\s*block\s*!important/)
  assert.doesNotMatch(appShell,/app-desktop-footer/)
  assert.doesNotMatch(appShell,/app-mobile-legal/)
})
