import Link from 'next/link'
import { AppShell } from '@/components/app-shell'
import { MoneyNav } from '@/components/money-nav'
import { SubmitButton } from '@/components/submit-button'
import { requireOnboardedUser } from '@/lib/auth'
import { taka } from '@/lib/format'
import { monthBounds, normalizeMoneyMonth, shiftMoneyMonth, summarizeBudget, summarizeMoney } from '@/lib/money.mjs'
import { dhakaToday, loadMoneyReference, moneyMonthLabel } from '@/lib/money-server'
import { copyPreviousMoneyBudgets, deleteMoneyBudget, saveMoneyBudget, saveMoneyGoal } from '@/app/actions/money'

export const dynamic='force-dynamic'
type Q={month?:string;error?:string;notice?:string}

export default async function BudgetsPage({searchParams}:{searchParams:Promise<Q>}){
  const {user,roles,supabase}=await requireOnboardedUser();const q=await searchParams;const bd=dhakaToday();const month=normalizeMoneyMonth(q.month,bd.month);const range=monthBounds(month);const ref=await loadMoneyReference(supabase,user.id)
  const [{data:txs},{data:budgets},{data:goals},{data:transfers}]=await Promise.all([
    supabase.from('money_transactions').select('transaction_type,amount,category_id,account_id,transaction_date').eq('user_id',user.id).gte('transaction_date',range.start).lt('transaction_date',range.next),
    supabase.from('money_budgets').select('*').eq('user_id',user.id).eq('month',range.start).order('created_at'),
    supabase.from('money_goals').select('*').eq('user_id',user.id),
    supabase.from('money_transfers').select('from_account_id,to_account_id,amount,transfer_date').eq('user_id',user.id).gte('transfer_date',range.start).lt('transfer_date',range.next),
  ])
  const rows=(txs??[]) as any[],budgetRows=(budgets??[]) as any[];const summary=summarizeMoney(rows,budgetRows),budgetSummary=summarizeBudget(rows,budgetRows);const catSpend=new Map<string,number>();rows.filter(r=>r.transaction_type==='expense').forEach(r=>catSpend.set(r.category_id,(catSpend.get(r.category_id)??0)+Number(r.amount)))
  const expenseCategories=(ref.categories as any[]).filter(c=>c.kind==='expense');const budgetIds=new Set(budgetRows.map(b=>b.category_id));const unbudgeted=rows.filter(r=>r.transaction_type==='expense'&&!budgetIds.has(r.category_id)).reduce((s,r)=>s+Number(r.amount),0)
  const savingsGoal=(goals??[]).find((g:any)=>g.goal_type==='savings'),emergencyGoal=(goals??[]).find((g:any)=>g.goal_type==='emergency');const prev=shiftMoneyMonth(month,-1),next=shiftMoneyMonth(month,1)
  return <AppShell roles={roles}><div className="grid gap-5"><MoneyNav/>
    <section className="glass-panel rounded-[26px] p-5"><div className="flex flex-wrap items-end justify-between gap-3"><div><div className="text-xs font-black uppercase tracking-[.15em] text-violet-700">Money</div><h1 className="mt-1 text-3xl font-black">Budgets</h1><p className="muted mt-1">Track category limits, savings and emergency targets.</p></div><div className="flex items-center gap-2"><Link className="btn-secondary" href={`/money/budgets?month=${prev}`}>←</Link><span className="chip">{moneyMonthLabel(month)}</span><Link className="btn-secondary" href={`/money/budgets?month=${next}`}>→</Link></div></div></section>
    {q.error&&<div className="error">{q.error}</div>}{q.notice&&<div className="success">{q.notice}</div>}
    <section className="card p-5"><div className="flex items-center justify-between gap-3"><div><div className="card-title">Savings & Emergency</div><p className="muted mt-1">Use any of your accounts as the target account.</p></div></div><div className="mt-4 grid gap-4 lg:grid-cols-2">{(['savings','emergency'] as const).map(type=>{const goal=type==='savings'?savingsGoal:emergencyGoal;return <form action={saveMoneyGoal} key={type} className="rounded-2xl border border-slate-200 bg-white/50 p-4"><input type="hidden" name="return_to" value="/money/budgets"/><input type="hidden" name="month" value={month}/><input type="hidden" name="goal_type" value={type}/><h2 className="font-black capitalize">{type}</h2><div className="mt-3 grid gap-3 sm:grid-cols-3"><select className="input" name="account_id" defaultValue={goal?.account_id??''}><option value="">No account selected</option>{(ref.accounts as any[]).map(a=><option key={a.id} value={a.id}>{a.name}</option>)}</select><input className="input" name="target_amount" type="number" step="0.01" min="0.01" defaultValue={goal?.target_amount??''} placeholder="Total target"/><input className="input" name="monthly_target" type="number" step="0.01" min="0.01" defaultValue={goal?.monthly_target??''} placeholder="Monthly target"/></div><div className="mt-3"><SubmitButton>Save {type} target</SubmitButton></div></form>})}</div></section>
    <section className="grid gap-3 sm:grid-cols-4"><div className="card p-4"><div className="card-title">Total budget</div><div className="metric mt-2">{taka(summary.budget)}</div></div><div className="card p-4"><div className="card-title">Budget spent</div><div className="metric mt-2">{taka(budgetSummary.budgetSpent)}</div></div><div className="card p-4"><div className="card-title">Remaining</div><div className={`metric mt-2 ${budgetSummary.budgetLeft<0?'text-rose-700':'text-emerald-700'}`}>{taka(budgetSummary.budgetLeft)}</div></div><div className="card p-4"><div className="card-title">Monthly income</div><div className="metric mt-2">{taka(summary.income)}</div></div></section>
    {unbudgeted>0&&<div className="rounded-xl border border-amber-300 bg-amber-50 p-4 text-sm text-amber-950"><b>Expense without budget:</b> {taka(unbudgeted)} this month.</div>}
    <section className="card p-5"><div className="flex flex-wrap items-end justify-between gap-3"><div><div className="card-title">Category budgets</div><h2 className="section-title mt-1">Plan this month</h2></div><form action={copyPreviousMoneyBudgets}><input type="hidden" name="month" value={month}/><input type="hidden" name="return_to" value="/money/budgets"/><button className="btn-secondary">Copy from previous month</button></form></div><form action={saveMoneyBudget} className="mt-5 grid gap-3 sm:grid-cols-[1fr_180px_auto] sm:items-end"><input type="hidden" name="month" value={month}/><input type="hidden" name="return_to" value="/money/budgets"/><select className="input" name="category_id" required><option value="">Choose category</option>{expenseCategories.map(c=><option key={c.id} value={c.id}>{c.icon??'•'} {c.name}</option>)}</select><input className="input" name="amount" type="number" min="1" step="0.01" placeholder="Budget ৳" required/><SubmitButton>Save budget</SubmitButton></form><div className="mt-5 grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{budgetRows.map((b:any)=>{const c=expenseCategories.find(x=>x.id===b.category_id),spent=catSpend.get(b.category_id)??0,amount=Number(b.amount),pct=amount?spent/amount*100:0,over=spent>amount;return <div className="rounded-2xl border border-slate-200 bg-white/50 p-4" key={b.id}><div className="flex items-start justify-between gap-3"><div><b>{c?.icon??'•'} {c?.name??'Category'}</b><p className="muted mt-1">Spent {taka(spent)} · Budget {taka(amount)}</p></div><form action={deleteMoneyBudget}><input type="hidden" name="id" value={b.id}/><input type="hidden" name="month" value={month}/><input type="hidden" name="return_to" value="/money/budgets"/><button className="text-xs font-bold text-rose-700">Delete</button></form></div><div className="mt-3 h-2 overflow-hidden rounded-full bg-slate-100"><div className={over?'h-full rounded-full bg-rose-500':'h-full rounded-full bg-violet-500'} style={{width:`${Math.min(100,Math.max(2,pct))}%`}}/></div><p className={over?'mt-2 text-xs font-bold text-rose-700':'mt-2 text-xs font-bold text-slate-600'}>{over?`${taka(spent-amount)} over`:`${taka(amount-spent)} remaining`} · {Math.round(pct)}%</p></div>})}</div></section>
  </div></AppShell>
}
