import type { Metadata } from 'next'
import Link from 'next/link'
import { PolicyPage } from '@/components/policy-page'
import { SITE_URL } from '@/lib/site'

export const metadata: Metadata = {
  title: 'Terms & Conditions | ব্যবহারের শর্তাবলি',
  description: 'Bilingual Terms & Conditions for the 2-TAKA-R-BAZAR community grocery pooling pilot in Savar, Bangladesh.',
  alternates: { canonical: `${SITE_URL}/terms` },
}

const sections = [
  {titleEn:'What the service is',titleBn:'সেবাটি কী',bodyEn:<p>2-TAKA-R-BAZAR coordinates community grocery demand, supplier negotiation and customer fulfilment. We are not the manufacturer of branded goods. Product availability depends on suppliers and confirmed community demand.</p>,bodyBn:<p>2-TAKA-R-BAZAR কমিউনিটির বাজারের চাহিদা একত্র করে, সরবরাহকারীর সাথে দরদাম করে এবং গ্রাহকের পণ্য হস্তান্তর সমন্বয় করে। আমরা ব্র্যান্ডেড পণ্যের প্রস্তুতকারক নই। পণ্যের প্রাপ্যতা সরবরাহকারী ও নিশ্চিত কমিউনিটি চাহিদার ওপর নির্ভর করে।</p>},
  {titleEn:'Commitment is not a purchase',titleBn:'কমিটমেন্ট মানেই ক্রয় নয়',bodyEn:<p>Joining a pool or entering a quantity records demand only. It becomes a purchase only when the final customer price is published and you explicitly confirm the purchase and choose FREE community collection or optional home delivery.</p>,bodyBn:<p>পুলে যোগ দেওয়া বা পরিমাণ দেওয়া শুধু চাহিদা হিসেবে ধরা হয়। চূড়ান্ত মূল্য প্রকাশের পর আপনি স্পষ্টভাবে ক্রয় নিশ্চিত করে বিনামূল্যের কমিউনিটি সংগ্রহ অথবা ঐচ্ছিক হোম ডেলিভারি বেছে নিলেই এটি অর্ডার হয়।</p>},
  {titleEn:'Price unlocks, final price and savings',titleBn:'প্রাইস আনলক, চূড়ান্ত মূল্য ও সাশ্রয়',bodyEn:<p>Volume tiers may unlock a maximum customer price. Once unlocked, that ceiling will not worsen for that pricing cycle. Final negotiation may keep or reduce the price. Market benchmarks are approved comparison references; verified product savings are credited only after successful fulfilment. Delivery charges are separate from product savings.</p>,bodyBn:<p>পরিমাণভিত্তিক টিয়ারে সর্বোচ্চ গ্রাহক মূল্য আনলক হতে পারে। একবার আনলক হলে সেই সাইকেলে মূল্যসীমা খারাপ হবে না। চূড়ান্ত দরদামে দাম একই থাকতে বা কমতে পারে। বাজার বেঞ্চমার্ক তুলনার অনুমোদিত রেফারেন্স; সফলভাবে পণ্য হস্তান্তরের পরই পণ্যের যাচাইকৃত সাশ্রয় যোগ হয়। ডেলিভারি চার্জ পণ্যের সাশ্রয় থেকে আলাদা।</p>},
  {titleEn:'Supplier availability and short supply',titleBn:'সরবরাহ ও ঘাটতি',bodyEn:<p>If a supplier cannot provide the confirmed quantity or acceptable goods, Operations may delay, replace the source, reduce fulfilment with your knowledge, or cancel the affected item. You will not be charged for an item that cannot be fulfilled.</p>,bodyBn:<p>সরবরাহকারী নিশ্চিত পরিমাণ বা গ্রহণযোগ্য পণ্য দিতে না পারলে Operations ডেলিভারি বিলম্ব করতে, অন্য উৎস নিতে, আপনাকে জানিয়ে পরিমাণ কমাতে বা সংশ্লিষ্ট আইটেম বাতিল করতে পারে। সরবরাহ করা না গেলে সেই আইটেমের মূল্য নেওয়া হবে না।</p>},
  {titleEn:'Fulfilment and inspection',titleBn:'পণ্য হস্তান্তর ও যাচাই',bodyEn:<p>Community delivery-point collection is free. Optional home delivery inside the community is charged separately at the rate shown before confirmation. Whether collecting or receiving at home, check quantity, visible damage and wrong items at handover where practical and report problems promptly under the <Link className="underline font-bold" href="/return-policy">Return Policy</Link>.</p>,bodyBn:<p>কমিউনিটি ডেলিভারি পয়েন্ট থেকে সংগ্রহ বিনামূল্যে। কমিউনিটির ভেতরে ঐচ্ছিক হোম ডেলিভারির চার্জ নিশ্চিত করার আগে আলাদাভাবে দেখানো হবে। পিকআপ বা হোম ডেলিভারি—দুই ক্ষেত্রেই সম্ভব হলে হস্তান্তরের সময় পরিমাণ, দৃশ্যমান ক্ষতি ও ভুল পণ্য যাচাই করুন এবং সমস্যা হলে দ্রুত <Link className="underline font-bold" href="/return-policy">রিটার্ন নীতি</Link> অনুযায়ী জানান।</p>},
  {titleEn:'Payment and delivery fees',titleBn:'পেমেন্ট ও ডেলিভারি ফি',bodyEn:<p>There is no subscription fee for community Pool access. Product price, product saving and any optional home-delivery charge are shown separately. Community delivery-point collection is free. Home delivery inside the community is ৳20 when the confirmed product subtotal is ৳1,000 or less and ৳30 when it is above ৳1,000, unless a later policy shown before confirmation replaces these rates.</p>,bodyBn:<p>কমিউনিটি Pool ব্যবহারের জন্য কোনো সাবস্ক্রিপশন ফি নেই। পণ্যমূল্য, পণ্যের সাশ্রয় এবং ঐচ্ছিক হোম ডেলিভারি চার্জ আলাদাভাবে দেখানো হয়। কমিউনিটি ডেলিভারি পয়েন্ট থেকে সংগ্রহ বিনামূল্যে। নিশ্চিত পণ্যের সাবটোটাল ৳১,০০০ বা কম হলে হোম ডেলিভারি ৳২০ এবং ৳১,০০০-এর বেশি হলে ৳৩০; ভবিষ্যতে কোনো পরিবর্তন হলে নিশ্চিত করার আগেই তা দেখানো হবে।</p>},
  {titleEn:'Returns and refunds',titleBn:'রিটার্ন ও রিফান্ড',bodyEn:<p>Returns and refunds are governed by the published <Link className="underline font-bold" href="/return-policy">Return Policy</Link> and <Link className="underline font-bold" href="/refund-policy">Refund Policy</Link>. Food-safety restrictions may limit change-of-mind returns after fulfilment.</p>,bodyBn:<p>রিটার্ন ও রিফান্ড প্রকাশিত <Link className="underline font-bold" href="/return-policy">রিটার্ন নীতি</Link> এবং <Link className="underline font-bold" href="/refund-policy">রিফান্ড নীতি</Link> অনুযায়ী হবে। খাদ্য নিরাপত্তার কারণে পণ্য হস্তান্তরের পর শুধু মত পরিবর্তনের ভিত্তিতে কিছু পণ্য ফেরত নেওয়া নাও হতে পারে।</p>},
  {titleEn:'Referral Coins',titleBn:'রেফারেল কয়েন',bodyEn:<p>Referral Coins are promotional, non-cash rewards. A referral reward is earned only after the referred neighbour completes the qualifying first completed order. Coins do not create a subscription entitlement. Any future Coin redemption benefit will be published before it becomes active.</p>,bodyBn:<p>Referral Coins প্রচারণামূলক, নগদে উত্তোলনযোগ্য নয়। রেফার করা প্রতিবেশীর প্রথম যোগ্য অর্ডার সফলভাবে সম্পন্ন হলে রেফারেল রিওয়ার্ড পাওয়া যায়। Coins কোনো সাবস্ক্রিপশন সুবিধা তৈরি করে না। ভবিষ্যতে Coin ব্যবহারের কোনো সুবিধা চালু হলে তা আগে প্রকাশ করা হবে।</p>},
  {titleEn:'Fair use and account responsibility',titleBn:'ন্যায্য ব্যবহার ও অ্যাকাউন্টের দায়িত্ব',bodyEn:<p>Use accurate mobile, community and fulfilment information. Duplicate, fake or self-referral activity may be rejected and related promotional rewards may be reversed. Do not misuse the platform or interfere with another household's order.</p>,bodyBn:<p>সঠিক মোবাইল, কমিউনিটি ও পণ্য হস্তান্তরের তথ্য ব্যবহার করুন। ডুপ্লিকেট, ভুয়া বা সেলফ-রেফারেল বাতিল হতে পারে এবং সংশ্লিষ্ট প্রচারণামূলক রিওয়ার্ড ফেরত নেওয়া হতে পারে। প্ল্যাটফর্ম অপব্যবহার বা অন্য পরিবারের অর্ডারে হস্তক্ষেপ করবেন না।</p>},
  {titleEn:'Delays and exceptional events',titleBn:'বিলম্ব ও ব্যতিক্রমী পরিস্থিতি',bodyEn:<p>Supplier disruption, weather, transport, public restrictions or other events outside reasonable control may change timing. We will communicate material changes and handle affected orders fairly rather than silently substituting price or product.</p>,bodyBn:<p>সরবরাহ সমস্যা, আবহাওয়া, পরিবহন, সরকারি বিধিনিষেধ বা যুক্তিসঙ্গত নিয়ন্ত্রণের বাইরে অন্য ঘটনায় সময় পরিবর্তিত হতে পারে। গুরুত্বপূর্ণ পরিবর্তন জানানো হবে; দাম বা পণ্য গোপনে বদলানো হবে না।</p>},
  {titleEn:'Policy updates and support',titleBn:'নীতির পরিবর্তন ও সহায়তা',bodyEn:<p>The current effective date is shown at the top of this page. Material changes apply prospectively. For an order issue, use the in-app issue reporting flow or an official 2-TAKA-R-BAZAR support channel.</p>,bodyBn:<p>এই পৃষ্ঠার ওপরে বর্তমান কার্যকর তারিখ দেওয়া আছে। গুরুত্বপূর্ণ পরিবর্তন ভবিষ্যৎ লেনদেনে প্রযোজ্য হবে। অর্ডার সংক্রান্ত সমস্যায় অ্যাপের issue report অথবা 2-TAKA-R-BAZAR-এর অফিসিয়াল সাপোর্ট চ্যানেল ব্যবহার করুন।</p>},
]

export default function TermsPage(){return <PolicyPage titleEn="Terms & Conditions" titleBn="ব্যবহারের শর্তাবলি" summaryEn="These terms explain how the community-pooling pilot works and when a commitment becomes a purchase." summaryBn="এই শর্তাবলি কমিউনিটি পুলিং পাইলট কীভাবে কাজ করে এবং কখন একটি কমিটমেন্ট ক্রয়ে পরিণত হয় তা ব্যাখ্যা করে।" sections={sections}/>} 
