import type { Metadata } from 'next'
import { PolicyPage } from '@/components/policy-page'
import { SITE_URL } from '@/lib/site'

export const metadata: Metadata = {title:'Refund Policy | রিফান্ড নীতি',description:'Bilingual refund policy for 2-TAKA-R-BAZAR community grocery pool orders.',alternates:{canonical:`${SITE_URL}/refund-policy`}}

const sections=[
  {titleEn:'When a refund may apply',titleBn:'কখন রিফান্ড প্রযোজ্য হতে পারে',bodyEn:<p>A refund may apply when an item or order is cancelled by Operations before fulfilment, a supplier shortfall prevents delivery, you were overcharged, or a verified wrong, missing, damaged or defective item cannot be satisfactorily replaced.</p>,bodyBn:<p>Operations পূরণের আগে আইটেম বা অর্ডার বাতিল করলে, সরবরাহ ঘাটতিতে ডেলিভারি না হলে, অতিরিক্ত টাকা নেওয়া হলে, অথবা যাচাইকৃত ভুল/কম/ক্ষতিগ্রস্ত/ত্রুটিযুক্ত পণ্য সন্তোষজনকভাবে বদলানো না গেলে রিফান্ড প্রযোজ্য হতে পারে।</p>},
  {titleEn:'Refund amount',titleBn:'রিফান্ডের পরিমাণ',bodyEn:<p>Approved refunds cover the affected item or quantity actually paid for. If a separately charged service or delivery fee directly relates to the failed fulfilment, Operations will review whether that affected fee should also be refunded.</p>,bodyBn:<p>অনুমোদিত রিফান্ড সংশ্লিষ্ট আইটেম বা বাস্তবে পরিশোধ করা পরিমাণের জন্য হবে। আলাদা সার্ভিস বা ডেলিভারি ফি ব্যর্থ fulfilment-এর সাথে সরাসরি সম্পর্কিত হলে সেই ফিও ফেরতযোগ্য কি না Operations যাচাই করবে।</p>},
  {titleEn:'When a refund normally does not apply',titleBn:'সাধারণত কখন রিফান্ড হয় না',bodyEn:<p>A correctly supplied and successfully collected item is not refundable solely because of a change of mind where the Return Policy excludes the return. Promotional Referral Coins are not cash and are not refundable as money.</p>,bodyBn:<p>রিটার্ন নীতিতে রিটার্ন গ্রহণযোগ্য না হলে সঠিকভাবে সরবরাহ ও সংগ্রহ করা পণ্য শুধু মত পরিবর্তনের কারণে রিফান্ডযোগ্য নয়। Promotional Referral Coins নগদ নয় এবং টাকা হিসেবে রিফান্ড করা যায় না।</p>},
  {titleEn:'Refund method',titleBn:'রিফান্ডের মাধ্যম',bodyEn:<p>Where possible, refunds will use the original payment method. If that is not practical, Operations may arrange an agreed Bangladesh mobile financial service, bank transfer or cash refund. We will never ask for your OTP or password to process a refund.</p>,bodyBn:<p>সম্ভব হলে যে মাধ্যমে পেমেন্ট হয়েছে সেই মাধ্যমেই রিফান্ড করা হবে। তা সম্ভব না হলে সম্মত বাংলাদেশি mobile financial service, ব্যাংক ট্রান্সফার বা নগদে ফেরত দেওয়া যেতে পারে। রিফান্ডের জন্য আমরা কখনো OTP বা পাসওয়ার্ড চাইব না।</p>},
  {titleEn:'Processing time',titleBn:'রিফান্ড প্রসেসিং সময়',bodyEn:<p>After a refund is approved and the required verification is complete, we aim to initiate it within 3 business days. Banks or payment providers may require additional processing time, which can extend the time before funds appear in your account.</p>,bodyBn:<p>রিফান্ড অনুমোদন ও প্রয়োজনীয় যাচাই শেষ হলে আমরা ৩ কর্মদিবসের মধ্যে রিফান্ড শুরু করার লক্ষ্য রাখি। ব্যাংক বা পেমেন্ট সেবাদাতার অতিরিক্ত প্রসেসিং সময় লাগতে পারে, ফলে অ্যাকাউন্টে টাকা দেখা দিতে আরও সময় লাগতে পারে।</p>},
  {titleEn:'Cancelled or unfulfilled pool items',titleBn:'বাতিল বা পূরণ না হওয়া পুল আইটেম',bodyEn:<p>If a confirmed pool item cannot be fulfilled, Operations will notify affected customers. Any amount already collected for the unfulfilled quantity will be refunded; an unavailable item must not silently be replaced with a higher-priced product without your agreement.</p>,bodyBn:<p>নিশ্চিত পুল আইটেম পূরণ করা না গেলে Operations সংশ্লিষ্ট গ্রাহকদের জানাবে। পূরণ না হওয়া পরিমাণের জন্য আগে টাকা নেওয়া থাকলে তা ফেরত দেওয়া হবে; আপনার সম্মতি ছাড়া অনুপলব্ধ পণ্য গোপনে বেশি দামের পণ্য দিয়ে বদলানো হবে না।</p>},
  {titleEn:'How to request or follow up',titleBn:'রিফান্ড অনুরোধ বা ফলোআপ',bodyEn:<p>Use the order's in-app <b>Report an issue</b> option and include the order code, affected item, quantity and a clear description. Keep any requested photo or packaging until Operations completes verification.</p>,bodyBn:<p>অর্ডারের <b>Report an issue</b> অপশন ব্যবহার করে অর্ডার কোড, সংশ্লিষ্ট আইটেম, পরিমাণ ও সমস্যার পরিষ্কার বিবরণ দিন। Operations যাচাই শেষ না করা পর্যন্ত চাওয়া ছবি বা প্যাকেট সংরক্ষণ করুন।</p>},
]

export default function RefundPolicyPage(){return <PolicyPage titleEn="Refund Policy" titleBn="রিফান্ড নীতি" summaryEn="This policy explains when money is returned, how the amount is determined and how refunds are processed during the pilot." summaryBn="এই নীতিতে পাইলট চলাকালে কখন টাকা ফেরত দেওয়া হয়, পরিমাণ কীভাবে নির্ধারিত হয় এবং রিফান্ড কীভাবে প্রসেস করা হয় তা বলা হয়েছে।" sections={sections}/>} 
