import { AppShell } from '@/components/app-shell'
import { MoneyNav } from '@/components/money-nav'
import { SubmitButton } from '@/components/submit-button'
import { requireOnboardedUser } from '@/lib/auth'
import { taka } from '@/lib/format'
import { dhakaToday, loadMoneyReference } from '@/lib/money-server'
import { deleteMoneyRecurring, postMoneyRecurringNow, saveMoneyRecurring } from '@/app/actions/money'

export const dynamic='force-dynamic'
type Q={error?:string;notice?:string}

export default async function RecurringPage({searchParams}:{searchParams:Promise<Q>}){
  const {user,roles,supabase}=await requireOnboardedUser();const q=await searchParams;const bd=dhakaToday();const ref=await loadMoneyReference(supabase,user.id)
  const {data:rows}=await supabase.from('money_recurring').select('*').eq('user_id',user.id).order('active',{ascending:false}).order('next_due_date')
  const expense=(ref.categories as any[]).filter(c=>c.kind==='expense'),income=(ref.categories as any[]).filter(c=>c.kind==='income')
  return <AppShell roles={roles}><div className="grid gap-5"><MoneyNav/>
    <section className="glass-panel rounded-[26px] p-5"><div className="text-xs font-black uppercase tracking-[.15em] text-violet-700">Organise</div><h1 className="mt-1 text-3xl font-black">Recurring</h1><p className="muted mt-1">Prepare rent, subscriptions, salary and other repeating money entries.</p></section>
    {q.error&&<div className="error">{q.error}</div>}{q.notice&&<div className="success">{q.notice}</div>}
    <form action={saveMoneyRecurring} className="card grid gap-3 p-5 md:grid-cols-2 xl:grid-cols-4"><input type="hidden" name="return_to" value="/money/recurring"/><label><span className="label">Type</span><select className="input" name="transaction_type" defaultValue="expense"><option value="expense">Expense</option><option value="income">Income</option></select></label><label><span className="label">Amount</span><input className="input" name="amount" type="number" min="0.01" step="0.01" required/></label><label><span className="label">Category</span><select className="input" name="category_id" required><option value="">Choose category</option><optgroup label="Expenses">{expense.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</optgroup><optgroup label="Income">{income.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</optgroup></select></label><label><span className="label">Account</span><select className="input" name="account_id" required>{(ref.accounts as any[]).map(a=><option key={a.id} value={a.id}>{a.name}</option>)}</select></label><label><span className="label">Person</span><select className="input" name="person_id" required>{(ref.people as any[]).map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></label><label><span className="label">Frequency</span><select className="input" name="frequency" defaultValue="monthly"><option value="weekly">Weekly</option><option value="monthly">Monthly</option><option value="yearly">Yearly</option></select></label><label><span className="label">Start date</span><input className="input" name="start_date" type="date" defaultValue={bd.today} required/></label><label><span className="label">End date</span><input className="input" name="end_date" type="date"/></label><label className="md:col-span-2"><span className="label">Description</span><input className="input" name="description" maxLength={120} placeholder="e.g. Monthly rent"/></label><label className="md:col-span-2"><span className="label">Note</span><input className="input" name="note" maxLength={300}/></label><div className="md:col-span-2 xl:col-span-4"><SubmitButton>Add recurring entry</SubmitButton></div></form>
    <section className="card overflow-hidden"><div className="divide-y divide-slate-200">{(rows??[]).length===0?<p className="muted p-6">No recurring entries yet.</p>:(rows??[]).map((row:any)=>{const c=(ref.categories as any[]).find(x=>x.id===row.category_id),a=(ref.accounts as any[]).find(x=>x.id===row.account_id),p=(ref.people as any[]).find(x=>x.id===row.person_id);return <div key={row.id} className="flex flex-wrap items-center gap-3 p-4"><div className="text-xl">↻</div><div className="min-w-0 flex-1"><b>{row.description||c?.name||'Recurring'}</b><p className="muted">{row.frequency} · next {row.next_due_date} · {a?.name} · {p?.name}</p></div><b>{row.transaction_type==='income'?'+':'−'}{taka(row.amount)}</b><span className={`chip ${row.active?'text-emerald-700':'text-slate-500'}`}>{row.active?'Active':'Ended'}</span>{row.active&&<form action={postMoneyRecurringNow}><input type="hidden" name="id" value={row.id}/><input type="hidden" name="transaction_date" value={bd.today}/><input type="hidden" name="return_to" value="/money/recurring"/><button className="btn-secondary">Post now</button></form>}<form action={deleteMoneyRecurring}><input type="hidden" name="id" value={row.id}/><input type="hidden" name="return_to" value="/money/recurring"/><button className="text-xs font-bold text-rose-700">Delete</button></form></div>})}</div></section>
  </div></AppShell>
}
