import { SuperAdminShell } from '@/components/super-admin-shell'
import { SubmitButton } from '@/components/submit-button'
import { requireSuperAdmin } from '@/lib/auth'
import { dateTime, shortDate, taka } from '@/lib/format'
import { createFreeCoupon, markMembershipInvoicePaid, updateSubscriptionSettings } from '@/app/actions/subscription'

export const dynamic='force-dynamic'
const num=(v:unknown)=>Number(v??0)||0

export default async function SubscriptionAdminPage({searchParams}:{searchParams:Promise<{error?:string;notice?:string}>}){
  const {supabase}=await requireSuperAdmin()
  const {error,notice}=await searchParams
  const [{data:settings},{data:coupons},{data:invoices},{data:memberships},{data:profiles}]=await Promise.all([
    supabase.from('subscription_settings').select('*').eq('singleton',true).single(),
    supabase.from('subscription_coupons').select('*').order('created_at',{ascending:false}),
    supabase.from('subscription_invoices').select('*').order('created_at',{ascending:false}).limit(100),
    supabase.from('subscription_memberships').select('*').order('valid_until',{ascending:false}),
    supabase.from('profiles').select('id,full_name,phone,onboarding_completed_at'),
  ])
  const profileById=new Map(((profiles??[]) as any[]).map(p=>[p.id,p]))
  const now=Date.now(),activeMembers=(memberships??[]).filter((m:any)=>m.valid_until&&new Date(m.valid_until).getTime()>now).length
  const pending=(invoices??[]).filter((i:any)=>i.status==='payment_pending'),unpaid=(invoices??[]).filter((i:any)=>i.status==='unpaid')
  const unpaidAmount=[...pending,...unpaid].reduce((s:any,i:any)=>s+num(i.amount),0)

  return <SuperAdminShell><div className="grid gap-5">
    <section><p className="text-xs font-black uppercase tracking-[0.18em] text-slate-500">Membership revenue</p><h1 className="mt-1 text-3xl font-black">Subscriptions & free coupons</h1><p className="muted mt-1">Set the monthly fee, control the pool-access gate, create 1/2/3-month promotions, and verify customer payments.</p></section>
    {error&&<div className="error">{error}</div>}{notice&&<div className="success">{notice}</div>}
    <section className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4">
      <div className="card"><div className="card-title">Gate status</div><div className="metric text-2xl">{settings?.enforcement_enabled?'Enforced':'Off'}</div><p className="muted mt-2">{settings?.enforcement_enabled?'Only active members can join/confirm pools.':'Customers are not blocked yet.'}</p></div>
      <div className="card"><div className="card-title">Monthly fee</div><div className="metric text-2xl">{settings?.monthly_price?taka(settings.monthly_price):'Not set'}</div><p className="muted mt-2">{settings?.currency??'BDT'}</p></div>
      <div className="card"><div className="card-title">Active memberships</div><div className="metric text-2xl">{activeMembers}</div><p className="muted mt-2">Paid or coupon entitlement still valid.</p></div>
      <div className="card"><div className="card-title">Open billing exposure</div><div className="metric text-2xl">{taka(unpaidAmount)}</div><p className="muted mt-2">{unpaid.length} unpaid · {pending.length} awaiting verification</p></div>
    </section>

    <section className="grid gap-4 xl:grid-cols-2">
      <form action={updateSubscriptionSettings} className="card grid gap-3"><div><div className="card-title">Billing settings</div><h2 className="section-title mt-1">Monthly membership</h2></div><label><span className="label">Monthly fee (BDT)</span><input className="input" type="number" min="1" step="0.01" name="monthly_price" defaultValue={settings?.monthly_price??''} required/></label><div className="grid gap-3 sm:grid-cols-2"><label><span className="label">Invoice lead days</span><input className="input" type="number" min="0" max="30" name="invoice_lead_days" defaultValue={settings?.invoice_lead_days??7}/></label><label><span className="label">Due days</span><input className="input" type="number" min="0" max="30" name="due_days" defaultValue={settings?.due_days??7}/></label></div><label><span className="label">Payment instructions</span><textarea className="input min-h-28" name="payment_instructions" defaultValue={settings?.payment_instructions??''} placeholder="Example: Pay by bKash/Nagad to ... then submit the transaction ID."/></label><label className="flex items-start gap-3 rounded-xl border border-slate-200 p-3"><input type="checkbox" name="enforcement_enabled" defaultChecked={Boolean(settings?.enforcement_enabled)} className="mt-1"/><span><b>Enforce membership before pool participation</b><span className="muted block mt-1">When enabled, customers without active paid/coupon access cannot commit or confirm purchases.</span></span></label><SubmitButton>Save subscription settings</SubmitButton></form>
      <form action={createFreeCoupon} className="card grid gap-3"><div><div className="card-title">Promotion</div><h2 className="section-title mt-1">Create free-use coupon</h2><p className="muted mt-2">Use for new customers, referrals, pilots, or campaigns.</p></div><label><span className="label">Coupon code</span><input className="input uppercase" name="code" required placeholder="WELCOME3"/></label><label><span className="label">Free months</span><select className="input" name="months_free" defaultValue="1"><option value="1">1 month</option><option value="2">2 months</option><option value="3">3 months</option></select></label><div className="grid gap-3 sm:grid-cols-2"><label><span className="label">Max redemptions</span><input className="input" type="number" min="1" name="max_redemptions" placeholder="Unlimited"/></label><label><span className="label">Expires at</span><input className="input" type="datetime-local" name="expires_at"/></label></div><label><span className="label">Notes</span><input className="input" name="notes" placeholder="Campaign or audience"/></label><label className="flex items-start gap-3 rounded-xl border border-slate-200 p-3"><input type="checkbox" name="new_customers_only" defaultChecked className="mt-1"/><span><b>New customers only</b><span className="muted mt-1 block">Blocks customers who already used a coupon or paid a subscription invoice.</span></span></label><SubmitButton>Create coupon</SubmitButton></form>
    </section>

    <section><div className="mb-3"><div className="card-title">Coupons</div><h2 className="section-title">Free-month campaigns</h2></div><div className="table-wrap"><table><thead><tr><th>Code</th><th>Free period</th><th>Audience</th><th>Used</th><th>Limit</th><th>Expires</th><th>Status</th></tr></thead><tbody>{(coupons??[]).length?(coupons??[]).map((c:any)=><tr key={c.id}><td><b>{c.code}</b><div className="muted">{c.notes??''}</div></td><td>{c.months_free} month{c.months_free===1?'':'s'}</td><td>{c.new_customers_only?'New customers':'Any eligible customer'}</td><td>{c.redeemed_count}</td><td>{c.max_redemptions??'Unlimited'}</td><td>{c.expires_at?dateTime(c.expires_at):'No expiry'}</td><td>{c.active?'Active':'Inactive'}</td></tr>):<tr><td colSpan={7} className="text-slate-500">No coupons created yet.</td></tr>}</tbody></table></div></section>

    <section><div className="mb-3"><div className="card-title">Customer bills</div><h2 className="section-title">Subscription invoices</h2></div><div className="table-wrap"><table><thead><tr><th>Invoice</th><th>Customer</th><th>Period</th><th>Amount</th><th>Status</th><th>Payment reference</th><th>Action</th></tr></thead><tbody>{(invoices??[]).length?(invoices??[]).map((i:any)=>{const p=profileById.get(i.customer_id);return <tr key={i.id}><td><b>{i.invoice_no}</b><div className="muted">Due {shortDate(i.due_at)}</div></td><td>{p?.full_name??'—'}<div className="muted">{p?.phone??''}</div></td><td>{shortDate(i.period_start)} → {shortDate(i.period_end)}</td><td>{taka(i.amount)}</td><td className="capitalize"><b>{i.status.replaceAll('_',' ')}</b></td><td>{i.payment_method??'—'}<div className="muted">{i.payment_reference??''}</div></td><td>{['unpaid','payment_pending'].includes(i.status)?<form action={markMembershipInvoicePaid} className="grid min-w-[190px] gap-2"><input type="hidden" name="invoice_id" value={i.id}/><input className="input min-h-9 py-1" name="payment_method" defaultValue={i.payment_method??'manual'} placeholder="Method"/><input className="input min-h-9 py-1" name="payment_reference" defaultValue={i.payment_reference??''} placeholder="Reference"/><SubmitButton className="btn-primary min-h-9 py-1">Confirm paid</SubmitButton></form>:i.paid_at?dateTime(i.paid_at):'—'}</td></tr>}):<tr><td colSpan={7} className="text-slate-500">No membership invoices yet.</td></tr>}</tbody></table></div></section>
    <section><div className="mb-3"><div className="card-title">Entitlements</div><h2 className="section-title">Membership access</h2></div><div className="table-wrap"><table><thead><tr><th>Customer</th><th>Valid until</th><th>Source</th><th>State</th></tr></thead><tbody>{(memberships??[]).length?(memberships??[]).map((m:any)=>{const p=profileById.get(m.user_id);const isActive=m.valid_until&&new Date(m.valid_until).getTime()>now;return <tr key={m.user_id}><td>{p?.full_name??'—'}<div className="muted">{p?.phone??''}</div></td><td>{m.valid_until?dateTime(m.valid_until):'—'}</td><td>{m.source??'—'}</td><td><b>{isActive?'Active':'Expired'}</b></td></tr>}):<tr><td colSpan={4} className="text-slate-500">No membership entitlements yet.</td></tr>}</tbody></table></div></section>

    <div className="notice"><b>Pool-access rule:</b> when enforcement is ON, browsing stays available, but the database blocks both commitment and final purchase confirmation unless the customer has a paid entitlement, a valid free-month coupon, or is Super Admin.</div>
  </div></SuperAdminShell>
}
