import { AdminShell } from '@/components/admin-shell'
import { Flash } from '@/components/flash'
import { SubmitButton } from '@/components/submit-button'
import { createSupplier, updateSupplier } from '@/app/actions/admin'
import { requireAdmin } from '@/lib/auth'

export const dynamic='force-dynamic'
export default async function Page({searchParams}:{searchParams:Promise<{error?:string;notice?:string}>}){
  const {supabase}=await requireAdmin();const sp=await searchParams
  const {data:rows}=await supabase.from('suppliers').select('*').order('created_at',{ascending:false})
  return <AdminShell><h1 className="text-3xl font-black mb-4">Suppliers</h1><Flash {...sp}/>
    <form action={createSupplier} className="card form-grid mb-5"><label><span className="label">Business name</span><input className="input" name="business_name" required/></label><label><span className="label">Contact person</span><input className="input" name="contact_person"/></label><label><span className="label">Mobile</span><input className="input" name="mobile"/></label><label><span className="label">Location</span><input className="input" name="location"/></label><label><span className="label">Product categories</span><input className="input" name="product_categories"/></label><label><span className="label">Reliability</span><select className="input" name="reliability_status"><option value="unrated">Unrated</option><option value="reliable">Reliable</option><option value="watch">Watch</option><option value="blocked">Blocked</option></select></label><textarea className="input min-h-20 md:col-span-2" name="notes" placeholder="Notes"/><SubmitButton>Create supplier</SubmitButton></form>
    <div className="grid gap-3">{rows?.map((r:any)=><details className="card" key={r.id}><summary className="cursor-pointer flex justify-between gap-3"><span><b>{r.business_name}</b> <span className="muted">· {r.location||'No location'} · {r.reliability_status}</span></span><span className="chip">{r.active?'Active':'Inactive'}</span></summary><form action={updateSupplier} className="form-grid mt-4"><input type="hidden" name="id" value={r.id}/><input className="input" name="business_name" defaultValue={r.business_name} required/><input className="input" name="contact_person" defaultValue={r.contact_person??''}/><input className="input" name="mobile" defaultValue={r.mobile??''}/><input className="input" name="location" defaultValue={r.location??''}/><input className="input" name="product_categories" defaultValue={r.product_categories??''}/><select className="input" name="reliability_status" defaultValue={r.reliability_status}><option value="unrated">Unrated</option><option value="reliable">Reliable</option><option value="watch">Watch</option><option value="blocked">Blocked</option></select><textarea className="input min-h-20 md:col-span-2" name="notes" defaultValue={r.notes??''}/><label className="flex items-center gap-2"><input type="checkbox" name="active" defaultChecked={r.active}/><span>Active</span></label><SubmitButton>Save supplier</SubmitButton></form></details>)}</div>
    <p className="muted mt-4">Supplier records used by quotations are retained for audit and can be deactivated.</p>
  </AdminShell>
}
