import type { Metadata } from 'next'
import { PublicHeader } from '@/components/public-header'
import { PublicFooter } from '@/components/public-footer'
import { SEO_UPDATED_AT, SITE_NAME, SITE_URL } from '@/lib/site'

export const metadata: Metadata = {title:'FAQ | প্রশ্নোত্তর',description:'Answers about 2-TAKA-R-BAZAR community grocery pools, final pricing, fulfilment, verified savings, returns and refunds.',alternates:{canonical:`${SITE_URL}/faq`}}

const faqs=[
  ['What is 2-TAKA-R-BAZAR?','2-TAKA-R-BAZAR is a community grocery-pooling service. Households combine demand, suppliers quote against the pooled volume, customers see the final price, then choose whether to confirm.','2-TAKA-R-BAZAR কী?','2-TAKA-R-BAZAR একটি কমিউনিটি গ্রোসারি পুলিং সেবা। পরিবারের চাহিদা একত্র হয়, মোট পরিমাণ অনুযায়ী সরবরাহকারীর দর নেওয়া হয়, গ্রাহক চূড়ান্ত দাম দেখে তারপর ক্রয় নিশ্চিত করেন।'],
  ['Does joining a pool mean I have bought the item?','No. A commitment records demand only. It becomes a purchase only after the final price is published and you explicitly confirm the purchase and choose FREE community collection or optional home delivery.','পুলে যোগ দিলেই কি অর্ডার হয়ে যায়?','না। কমিটমেন্ট শুধু চাহিদা রেকর্ড করে। চূড়ান্ত দাম প্রকাশের পর আপনি ক্রয় নিশ্চিত করে বিনামূল্যের কমিউনিটি সংগ্রহ বা ঐচ্ছিক হোম ডেলিভারি বেছে নিলেই অর্ডার হয়।'],
  ['How does the price unlock work?','Higher confirmed community demand can unlock a lower customer price ceiling. Once a tier is earned for that pricing cycle, final supplier negotiation may keep or improve the price but cannot worsen the earned ceiling.','প্রাইস আনলক কীভাবে কাজ করে?','কমিউনিটির নিশ্চিত চাহিদা বাড়লে কম দাম আনলক হতে পারে। একটি টিয়ার অর্জিত হলে চূড়ান্ত দরদামে দাম একই থাকতে বা আরও কমতে পারে, কিন্তু অর্জিত সীমার চেয়ে খারাপ হবে না।'],
  ['How are savings calculated?','The app compares the approved local-market benchmark captured for the pool with the final customer price. Product savings become verified only after successful fulfilment; delivery charges are separate.','সাশ্রয় কীভাবে হিসাব হয়?','অ্যাপ পুলের জন্য অনুমোদিত স্থানীয় বাজার বেঞ্চমার্কের সাথে চূড়ান্ত গ্রাহক মূল্য তুলনা করে। সফলভাবে পণ্য হস্তান্তরের পরই পণ্যের সাশ্রয় যাচাইকৃত হয়; ডেলিভারি চার্জ আলাদা।'],
  ['Where is the pilot running?','The first controlled pilot is focused on Amin Model Town / Pollibiddut in Savar, Bangladesh, with expansion only after the operating model is proven.','পাইলট কোথায় চলছে?','প্রথম নিয়ন্ত্রিত পাইলট Savar-এর Amin Model Town / Pollibiddut এলাকায় কেন্দ্রীভূত। অপারেশন প্রমাণিত হওয়ার পরই অন্য এলাকায় সম্প্রসারণ হবে।'],
  ['How does fulfilment work?','The supplier delivers consolidated goods to the community receiving point first. After Operations verifies receipt, customers either collect FREE from an enabled community point or receive optional home delivery. Home delivery is ৳20 for a confirmed product subtotal of ৳1,000 or less and ৳30 above ৳1,000.','পণ্য কীভাবে পাব?','সরবরাহকারী প্রথমে কমিউনিটি receiving point-এ একত্রিত পণ্য দেয়। Operations যাচাই করার পর গ্রাহক বিনামূল্যে নির্ধারিত কমিউনিটি পয়েন্ট থেকে সংগ্রহ করতে পারেন অথবা ঐচ্ছিক হোম ডেলিভারি নিতে পারেন। নিশ্চিত পণ্যের সাবটোটাল ৳১,০০০ বা কম হলে হোম ডেলিভারি ৳২০ এবং বেশি হলে ৳৩০।'],
  ['What if an item is wrong, missing or damaged?','Report it at handover where practical or through the in-app issue flow promptly. The Return and Refund Policies explain the available remedy and timing.','পণ্য ভুল, কম বা ক্ষতিগ্রস্ত হলে কী করব?','সম্ভব হলে হস্তান্তরের সময় জানান অথবা দ্রুত অ্যাপের issue flow ব্যবহার করুন। Return এবং Refund Policy-তে সমাধান ও সময়সীমা দেওয়া আছে।'],
]

export default function FaqPage(){
  const schema={"@context":"https://schema.org","@type":"FAQPage","@id":`${SITE_URL}/faq#faq`,url:`${SITE_URL}/faq`,name:'Frequently asked questions',dateModified:SEO_UPDATED_AT,isPartOf:{"@id":`${SITE_URL}/#website`},breadcrumb:{"@id":`${SITE_URL}/faq#breadcrumb`},mainEntity:faqs.map(([q,a])=>({"@type":"Question",name:q,acceptedAnswer:{"@type":"Answer",text:a}}))}
  const breadcrumb={"@context":"https://schema.org","@type":"BreadcrumbList","@id":`${SITE_URL}/faq#breadcrumb`,itemListElement:[{"@type":"ListItem",position:1,name:'Home',item:SITE_URL},{"@type":"ListItem",position:2,name:'FAQ',item:`${SITE_URL}/faq`}]}
  return <main className="min-h-screen bg-slate-50 text-slate-950"><PublicHeader actionHref="/" actionLabel="Home"/><script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(schema)}}/><script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(breadcrumb)}}/>
    <div className="mx-auto max-w-4xl px-4 py-8 sm:px-6 sm:py-12"><p className="text-xs font-black uppercase tracking-[0.18em] text-slate-500">{SITE_NAME}</p><h1 className="mt-2 text-3xl font-black sm:text-4xl">Frequently asked questions</h1><p className="mt-1 text-xl font-bold text-slate-700" lang="bn">সাধারণ প্রশ্নোত্তর</p><div className="mt-6 grid gap-4">{faqs.map(([q,a,qb,ab])=><article key={q} className="rounded-2xl border border-slate-200 bg-white p-5"><h2 className="font-black">{q}</h2><p className="mt-2 leading-7 text-slate-700">{a}</p><h3 className="mt-4 font-bold" lang="bn">{qb}</h3><p className="mt-2 leading-7 text-slate-700" lang="bn">{ab}</p></article>)}</div></div><PublicFooter/></main>
}
