import type { Metadata } from 'next'
import Link from 'next/link'
import { PolicyPage } from '@/components/policy-page'
import { SITE_URL } from '@/lib/site'

export const metadata: Metadata = {title:'Return Policy | রিটার্ন নীতি',description:'Bilingual return policy for 2-TAKA-R-BAZAR community grocery pickup orders.',alternates:{canonical:`${SITE_URL}/return-policy`}}

const sections=[
  {titleEn:'Check at pickup',titleBn:'পিকআপের সময় যাচাই',bodyEn:<p>Please check item, quantity, package condition and obvious damage at handover where practical. If something is wrong, tell Pickup Operations before leaving or report it in the app as soon as possible.</p>,bodyBn:<p>সম্ভব হলে পণ্য নেওয়ার সময় আইটেম, পরিমাণ, প্যাকেটের অবস্থা ও দৃশ্যমান ক্ষতি যাচাই করুন। সমস্যা থাকলে পিকআপ পয়েন্ট ছাড়ার আগে জানান অথবা যত দ্রুত সম্ভব অ্যাপে রিপোর্ট করুন।</p>},
  {titleEn:'Wrong, missing or visibly damaged goods',titleBn:'ভুল, কম বা দৃশ্যমানভাবে ক্ষতিগ্রস্ত পণ্য',bodyEn:<p>Report a wrong, missing, leaking, broken or visibly damaged item at pickup where practical, or within 2 hours of collection. We may ask for a photo, order code or the affected item so Operations can verify the issue.</p>,bodyBn:<p>ভুল, কম, লিক হওয়া, ভাঙা বা দৃশ্যমানভাবে ক্ষতিগ্রস্ত পণ্য সম্ভব হলে পিকআপের সময়, না হলে সংগ্রহের ২ ঘণ্টার মধ্যে জানান। যাচাইয়ের জন্য ছবি, অর্ডার কোড বা সংশ্লিষ্ট পণ্য চাইতে পারি।</p>},
  {titleEn:'Packaged grocery quality issues',titleBn:'প্যাকেটজাত মুদি পণ্যের সমস্যা',bodyEn:<p>For expired, spoiled, unsealed or otherwise defective packaged grocery items that were not reasonably visible at handover, report the issue within 24 hours of collection and keep the packaging where possible.</p>,bodyBn:<p>মেয়াদোত্তীর্ণ, নষ্ট, সিল খোলা বা অন্য ত্রুটিযুক্ত প্যাকেটজাত মুদি পণ্যের সমস্যা হস্তান্তরের সময় বোঝা না গেলে সংগ্রহের ২৪ ঘণ্টার মধ্যে জানান এবং সম্ভব হলে প্যাকেট সংরক্ষণ করুন।</p>},
  {titleEn:'Perishable items',titleBn:'পচনশীল পণ্য',bodyEn:<p>For eggs, fresh produce or other perishables, report quality or damage issues within 2 hours of collection. Because condition can change quickly after handover, later claims may be difficult to verify.</p>,bodyBn:<p>ডিম, তাজা পণ্য বা অন্যান্য পচনশীল পণ্যের মান বা ক্ষতির সমস্যা সংগ্রহের ২ ঘণ্টার মধ্যে জানান। হস্তান্তরের পর দ্রুত অবস্থার পরিবর্তন হতে পারে বলে দেরিতে করা অভিযোগ যাচাই করা কঠিন হতে পারে।</p>},
  {titleEn:'Change-of-mind returns',titleBn:'মত পরিবর্তনের কারণে রিটার্ন',bodyEn:<p>Opened food, perishables and goods that cannot safely be resold are not returnable only because you changed your mind. Unused non-food items in original sealed condition may be requested for return within 3 calendar days, subject to inspection.</p>,bodyBn:<p>খোলা খাদ্যপণ্য, পচনশীল পণ্য বা নিরাপদে পুনরায় বিক্রি করা যায় না এমন পণ্য শুধু মত পরিবর্তনের কারণে ফেরত নেওয়া হবে না। অব্যবহৃত non-food পণ্য মূল সিল অবস্থায় থাকলে ৩ ক্যালেন্ডার দিনের মধ্যে যাচাই সাপেক্ষে রিটার্ন অনুরোধ করা যেতে পারে।</p>},
  {titleEn:'Available remedies',titleBn:'সমাধানের ধরন',bodyEn:<p>Depending on the verified problem and stock, the remedy may be replacement, corrected quantity, partial refund or full refund for the affected item. Store credit will be used only if you agree.</p>,bodyBn:<p>যাচাইকৃত সমস্যা ও স্টক অনুযায়ী সমাধান হতে পারে বদলি পণ্য, ঘাটতি পূরণ, আংশিক রিফান্ড বা সংশ্লিষ্ট আইটেমের পূর্ণ রিফান্ড। আপনার সম্মতি ছাড়া store credit দেওয়া হবে না।</p>},
  {titleEn:'How to request a return',titleBn:'রিটার্ন কীভাবে চাইবেন',bodyEn:<p>Use the order's in-app <b>Report an issue</b> option or contact Pickup Operations with the order code and problem. Approved physical returns will be handed back at the designated pickup point or another location agreed by Operations. See the <Link className="underline font-bold" href="/refund-policy">Refund Policy</Link> for money-return timing.</p>,bodyBn:<p>অর্ডারের <b>Report an issue</b> অপশন ব্যবহার করুন অথবা অর্ডার কোড ও সমস্যার বিবরণসহ Pickup Operations-কে জানান। অনুমোদিত পণ্য নির্ধারিত পিকআপ পয়েন্টে বা Operations-এর সাথে সম্মত স্থানে ফেরত দেওয়া হবে। টাকা ফেরতের সময় জানতে <Link className="underline font-bold" href="/refund-policy">রিফান্ড নীতি</Link> দেখুন।</p>},
]

export default function ReturnPolicyPage(){return <PolicyPage titleEn="Return Policy" titleBn="রিটার্ন নীতি" summaryEn="We prioritise fast resolution for wrong, missing, damaged or defective goods while respecting food-safety limits." summaryBn="ভুল, কম, ক্ষতিগ্রস্ত বা ত্রুটিযুক্ত পণ্য দ্রুত সমাধান করা আমাদের অগ্রাধিকার; একই সঙ্গে খাদ্য নিরাপত্তার সীমা মানা হয়।" sections={sections}/>} 
